---
title: "Midcourse"
output: html_document
---
```{r}
library(httr)
library(tidyverse)
library(jsonlite)
library(lubridate)
library(ggthemes)
```
#Using API to get Metro Nashivlle Traffic data for 2018
```{r}
url = 'https://data.nashville.gov/resource/6v6w-hpcw.json?$limit=300000'

query = list(
  '$where'= 'date_and_time between "2018-01-01T00:00:00" and "2018-12-31T23:59:59"'
) 

response <- GET(url, query = query)
```

```{r}
response$status_code
```

#Convert to tibble
```{r}
traffic <-content(response, as = 'text') %>% 
  fromJSON()
```

#Remove some columns
```{r}
traffic <- traffic %>% 
  select(-c(reporting_officer,illuaccidemination,harmfulcodes, state, rpa, precinct,weather, collision_type,   collision_type_description,harmfuldescriptions))
```
```{r}
traffic %>% 
  object.size()
```
```{r}
traffic <- traffic %>% 
  mutate(weather_description = factor(weather_description),
        illumination_description = factor(illumination_description),
        street_address = factor(street_address),
        city = factor(city),
        zip = factor(zip))
```
```{r}
traffic %>% 
  write_rds('data/traffic.RDS')
```


```{r}
traffic <- read_rds('data/traffic.RDS')
```


#API for Calls for Service for 2018
```{r}
url = 'https://data.nashville.gov/resource/kwnd-qrrm.json?$limit=30000000'

query = list(
  '$where'= 'call_rec between "2018-01-01T00:00:00" and "2018-12-31T23:59:59"'
)

response <- GET(url, query = query)
```
#Change to tibble and remove columns 
```{r}
calls <- content(response, as = 'text')  %>% 
  fromJSON()
```
```{r}
calls <- calls %>% 
  select(-c(disposition_code, disposition_description, unit_dispatched, shift,
            sector, zone, rpa, lat, lon, mapped_location, tencode_suf, tencode_suf_description, complaint))
```
```{r}
calls %>% 
  object.size()
```
```{r}
calls <- calls %>% 
  mutate(event_number = factor(event_number),
        tencode = factor(tencode),
        description = factor(description))
```

```{r}
calls %>% 
  write_rds('data/calls.RDS')

calls <- read_rds('data/calls.RDS')
calls
```


#Convert timestamps from characters 
```{r}
calls$call_rec <- as.POSIXct(calls$call_rec, format = "%Y-%m-%dT%H:%M:%OS")

traffic$date_and_time <- as.POSIXct(traffic$date_and_time, format = "%Y-%m-%dT%H:%M:%OS")
```
#Subsetting calls to test
```{r}
calls %>% 
  filter(call_rec >= as.POSIXct( '2018-03-11 00:00:00') &
         call_rec <= as.POSIXct( '2018-03-12 00:00:14')
  )
```
#top 10 tencodes for 2018
```{r}
top10_tencode <- calls %>% 
  group_by(tencode) %>% 
  summarize(count = n()) %>%
  top_n(n =10, wt= count) %>% 
  ggplot(aes(x=tencode, y=count)) +
    geom_col()
top10_tencode
```

```{r}
calls %>% 
  group_by(tencode) %>% 
  summarize(count = n()) %>%
  top_n(n =10, wt= count) %>% 
  arrange(desc(count))
```
```{r}
jan_calls <- calls %>% 
  filter(month(call_rec) == 1) %>% 
  count()

jan_calls
```

#starting aggregate count by month for 2018 for number of accidents
```{r}
traffic %>% 
  filter(date_and_time >= as.POSIXct( '2018-03-11 00:00:00') &
         date_and_time <= as.POSIXct( '2018-03-13 00:00:14')
  )

```


```{r}
traffic %>% 
  filter(month(date_and_time) == 2)
```

#2018 total traffic accidents by month
```{r}
traffic$date_and_time_formatted <- format(traffic$date_and_time, "%b")

traffic %>% 
  group_by(date_and_time_formatted) %>% 
  summarize(frequency = n()) %>%
  ggplot(aes(x=factor(date_and_time_formatted,levels = month.abb), y=frequency)) +
    geom_col() +
    theme(axis.title.x=element_blank())
```
```{r}
head(traffic)
```

```{r}
traffic %>% 
  filter(month(date_and_time) == 1) %>% 
  summarize("Number of injuries" = sum(as.numeric(number_of_injuries)),
            "Number of Vehicles Involved" = sum(as.numeric(number_of_motor_vehicles)),
            "Instances of Property Damage" = sum(property_damage, na.rm = T),
            "Instances of Hit and Run" = sum(hit_and_run),
            "Max Number of Vehicles Involved" = max(as.numeric(number_of_motor_vehicles),na.rm = T)
            )
```
```{r}
traffic %>% 
  filter(week(date_and_time) == 10) %>% 
  summarize("Number of injuries" = sum(as.numeric(number_of_injuries)),
            "Number of Vehicles Involved" = sum(as.numeric(number_of_motor_vehicles)),
            "Instances of Property Damage" = sum(property_damage, na.rm = T),
            "Instances of Hit and Run" = sum(hit_and_run),
            "Max Number of Vehicles Involved" = max(as.numeric(number_of_motor_vehicles),na.rm = T)
            )
```


```{r}
jan_traffic <- traffic %>% 
  filter(month(date_and_time) == 1)

feb_traffic <- traffic %>% 
  filter(month(date_and_time) == 2)

march_traffic <- traffic %>% 
  filter(month(date_and_time) == 3)

april_traffic <- traffic %>% 
  filter(month(date_and_time) == 4)

may_traffic <- traffic %>% 
 filter(month(date_and_time) == 5) 

june_traffic <- traffic %>% 
 filter(month(date_and_time) == 6)

july_traffic <- traffic %>% 
 filter(month(date_and_time) == 7)

aug_traffic <- traffic %>% 
  filter(month(date_and_time) == 8)

sept_traffic <- traffic %>% 
  filter(month(date_and_time) == 9)

oct_traffic <- traffic %>% 
  filter(month(date_and_time) == 10)

nov_traffic <- traffic %>% 
  filter(month(date_and_time) == 11)

dec_traffic <- traffic %>% 
  filter(month(date_and_time) == 12)
```

```{r}
month_test <- floor_date(dec_traffic$date_and_time, "week", week_start = getOption("lubridate.week.start",6)) 

jan_traffic %>%   
  group_by(month=floor_date(date_and_time, "week", week_start = getOption("lubridate.week.start",7))) %>% 
  summarize(mean=mean(as.numeric(number_of_injuries)))
  
```


```{r}
jan_traffic %>%   
  group_by(week=week(jan_traffic$date_and_time)) %>% 
  summarize(Number_of_injuries=sum(as.numeric(number_of_injuries))) %>% 
  ggplot(aes(x= week,y=Number_of_injuries)) +
      geom_col() +
      theme_few() +
      theme(legend.position = "none")
```
```{r}
calls$call_rec_formatted <- format(calls$call_rec, "%b")


calls %>% 
  group_by(call_rec_formatted) %>% 
  summarize(frequency = n()) %>%
  ggplot(aes(x=factor(call_rec_formatted,levels = month.abb), y=frequency)) +
    geom_col() +
    theme(axis.title.x=element_blank())
```

